"""Command-line interface for the ExpertCook expert system.

Run it with:

    venv/Scripts/python.exe cli.py

It asks which dish you want, collects a few parameters (RICE FIRST - it is the
base everything else is derived from), then prints an ordered cooking guide
generated by the experta rules.
"""

import sys

from expertcook.recipes import DISHES, PARAM_SPECS
from expertcook.planner import build_plan


def _reconfigure_stdout():
    """Make the Windows console print UTF-8 instead of crashing on cp1252."""
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass  # older Python or a stream that can't be reconfigured - ignore


def _prompt(text):
    """input() that treats end-of-input (piped/empty) as 'use the default'."""
    try:
        return input(text).strip()
    except EOFError:
        print("")
        return ""


def ask_choice(spec):
    choices = spec["choices"]
    default = spec["default"]
    print("\n%s  (%s)" % (spec["label"], spec.get("help", "")))
    for i, choice in enumerate(choices, 1):
        marker = "  [default]" if choice == default else ""
        print("  %d) %s%s" % (i, choice, marker))
    while True:
        raw = _prompt("Choose 1-%d [%s]: " % (len(choices), default))
        if raw == "":
            return default
        if raw.isdigit() and 1 <= int(raw) <= len(choices):
            return choices[int(raw) - 1]
        if raw in choices:
            return raw
        print("  Please enter a number 1-%d or one of: %s"
              % (len(choices), ", ".join(choices)))


def ask_number(spec):
    default = spec["default"]
    lo = spec.get("min", 1)
    while True:
        raw = _prompt("\n%s (>= %s) [%s]: " % (spec["label"], lo, default))
        if raw == "":
            return default
        try:
            val = float(raw)
            if spec["type"] == "int":
                if abs(val - round(val)) > 1e-9:
                    raise ValueError
                val = int(val)
        except ValueError:
            print("  Please enter a number.")
            continue
        if val < lo:
            print("  Must be at least %s." % lo)
            continue
        return val


def choose_dish():
    keys = list(DISHES)
    print("What would you like to cook?")
    for i, key in enumerate(keys, 1):
        print("  %d) %s" % (i, DISHES[key]))
    while True:
        raw = _prompt("Choose 1-%d [1]: " % len(keys))
        if raw == "":
            return keys[0]
        if raw.isdigit() and 1 <= int(raw) <= len(keys):
            return keys[int(raw) - 1]
        if raw in DISHES:
            return raw
        print("  Please enter a number 1-%d." % len(keys))


def prompt_params(dish):
    params = {}
    for spec in PARAM_SPECS[dish]:
        if spec["type"] == "choice":
            params[spec["name"]] = ask_choice(spec)
        else:
            params[spec["name"]] = ask_number(spec)
    return params


def print_plan(plan):
    bar = "=" * 60
    print("\n" + bar)
    print("  COOKING GUIDE: %s" % plan["dish"])
    print(bar)
    for line in plan["summary"]:
        print("  " + line)
    print("-" * 60)
    print("  INGREDIENTS (rice is the base):")
    for ing in plan["ingredients"]:
        amt = ing["amount"] if ing["amount"] is not None else "to taste"
        unit = ing["unit"]
        line = "    - %s: %s%s" % (ing["label"], amt,
                                   (" " + unit) if unit else "")
        if ing.get("note"):
            line += "   (%s)" % ing["note"]
        print(line)
    print("-" * 60)
    for i, step in enumerate(plan["steps"], 1):
        head = "Step %d" % i
        if step["phase"]:
            head += " - %s" % step["phase"]
        print("\n%s" % head)
        for line in step["text"].splitlines():
            print("  " + line)
    print("\n" + bar)
    print("  Enjoy your meal!")
    print(bar + "\n")


def main():
    _reconfigure_stdout()
    print("=" * 60)
    print("  ExpertCook - Nigerian Rice Dishes Expert System")
    print("  Rice is the base: every quantity follows from it")
    print("=" * 60 + "\n")
    dish = choose_dish()
    params = prompt_params(dish)
    try:
        plan = build_plan(dish, params)
    except ValueError as exc:
        print("\nCould not build the guide: %s" % exc)
        return 1
    print_plan(plan)
    return 0


if __name__ == "__main__":
    sys.exit(main())
